### ISSUE TITLE
srcomapi get player location

### ISSUE THREAD

**Issue by anatomecha** [softloud/supermetroid#2]
getting user location and data from srcomapi 
https://github.com/blha303/srcomapi
```
import srcomapi, srcomapi.datatypes as dt

api = srcomapi.SpeedrunCom(); api.debug = 1

#given an id get the player location and handle
user = api.get_user("8rl93kw8")
user.name
user.location
user.data.keys()
user.data['names']
user.data['location']
```

**Comment by softloud** [comment]
This is so useful! :hugs: 

Unfortunately, not all players's id are valid api calls. So the quest to construct a list of players' data continues.

```
# get api
src_api = srcomapi.SpeedrunCom(); api.debug = 1

# this for loop fails because not all ids are valid (try running on first 3 entries)

# get valid records for players
src_players = []

# get a list of player records for each valid player id
for player in player_api_valid.player:
  user = src_api.get_user(player)
  src_players.append(user)

# APIRequestException: (404, 'Not Found', 'users/DasBlurr')

# it does work for the first three records
for player in player_api_valid.player[0:3]:
  print(player)
  user = src_api.get_user(player)
  src_players.append(user)

# when we search on player ids for strings not equal to 8, we see some ids are user handles
src_run_df.assign(id_len = lambda x: x.player.str.len()).query('id_len != 8').player
```

How can we write a try-catch that does this:
1. if an error is not thrown by `src_api.get_user.player` append list with that user 
2. if an error is thrown _and_ but an error is not thrown by calling the api on username, use that to retrieve user
3. if an error is thrown by both user id and user name, return NA or None or whatever python likes, python missing data thing

**Comment by softloud** [comment]
Useful code, thanks @anatomecha :+1: 

Try-except incorporated into code in src.Rmd vignette.
